config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sessions#new"

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"

  post "login", to: "sessions#create"
  get "login", to: "sessions#new"
  delete "logout", to: "sessions#destroy"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  
  resources :users do
    resources :pokemons
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :pokemons

    CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
    PASSWORD_REST_TOKEN_EXPIRATION = 10.minutes
    MAILER_FROM_EMAIL = "no-reply@example.com"
  
    has_secure_password
  
    before_save :downcase_email
  
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true

    def send_password_reset_email
      password_reset_token = generate_password_reset_token
      UserMailer.password_reset(self, password_reset_token).deliver_now
    end

    def send_confirmation_email
      confirmation_token = generate_confirmation_token
      UserMailer.confirmation(self, confirmation_token).deliver_now
    end
  
    def confirm!
      update_columns(confirmed_at: Time.current)
    end
  
    def confirmed?
      confirmed_at.present?
    end

    def generate_password_reset_token
      signed_id expires_in: PASSWORD_REST_TOKEN_EXPIRATION, purpose: :reset_password
    end
  
    def generate_confirmation_token
      signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
    end
  
    def unconfirmed?
      !confirmed?
    end
  
    private
  
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_authenticated, only: [:create, :new]
  before_action :authenticate_user, only: [:index]
  
  def index
    @numero_pokemones = POKEMON_COUNT
    @pokemon_id = rand(@numero_pokemones)
    @abilities = PokeApi.get(pokemon: @pokemon_id).abilities
    @types = PokeApi.get(pokemon: @pokemon_id).types
    @moves = PokeApi.get(pokemon: @pokemon_id).moves
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    puts user_params
    if @user.save
      @user.send_confirmation_email
      redirect_to root_path, notice: "Please check your email for confirmation instructions"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div style="overflow-y: auto;">
  <center>
    <div style="position: fixed; right: 0;">
      <%= button_to "Log Out", '/logout', method: :delete, class: 'button-77' %>
    </div>  

    <div style="display: flex; flex-direction: row; justify-content: center;">
      <img src=<%= PokeApi.get(pokemon: @pokemon_id).sprites.front_default %>
        width="10%"
        height="10%" />

      <h1><%= PokeApi.get(pokemon: @pokemon_id).name %></h1>

      <img src=<%= PokeApi.get(pokemon: @pokemon_id).sprites.back_default %>
        width="10%"
        height="10%" />
    </div>  

    <div style="display: flex; flex-direction: row; justify-content: center;">
      <div>
        <h3>Information</h3>
        <table class="styled-table">
          <thead>
            <tr>
              <th>Weight</th>
              <th>Types</th>
              <th>Habilities</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= PokeApi.get(pokemon: @pokemon_id).weight %></td>
              <td>
                <table class="styled-table">
                  <tbody>
                    <tr>
                      <% @types.each do |type| %>
                        <td>
                          <%= type.type.name %>
                        </td>
                      <% end %>
                    </tr>
                  </tbody>
                </table>
              </td>
              <td>
                <table class="styled-table">
                  <tbody>
                    <tr>
                      <% @abilities.each do |ability| %>
                        <td>
                          <%= ability.ability.name %>
                        </td>
                      <% end %>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      &nbsp
      <div>
        <h3>Moves</h3>

        <table class="styled-table">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @moves[0].move.name %></td>
            </tr>
            <tr>
              <td><%= @moves[1].move.name %></td>
            </tr>
            <tr>
              <td><%= @moves[2].move.name %></td>
            </tr>
            <tr>
              <td><%= @moves[3].move.name %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>  

    <div style="display: flex; flex-direction: row; position: fixed; bottom: 0; right: 0; bottom: 0; justify-content: center;">
      <%= form_with model: [Current.user, Current.user.pokemons.build] do |form| %>
      <div>
      <%= form.hidden_field :pokemon_id, value: @pokemon_id%>
      </div>
      <div>
        <button onclick="form.submit" class="button-77" role="button">Capture Pokemon</button>
      </div>
      <% end %>
      <%= button_to "Ignore Pokemon", '/users', method: :get, class: 'button-77' %>
    </div>  

    <h3>Pokemon caught</h3>

    <table class="styled-table">
      <thead>
        <tr>
          <th>Pokemon name</th>
          <th>Pokedex number</th>
          <th>Image</th>
        </tr>
      </thead>
      <tbody>
        <% Current.user.pokemons.each do |pokemon| %>
        <% if (pokemon.pokemon_id != nil) %>
          <tr>
            <td><%= PokeApi.get(pokemon: pokemon.pokemon_id).name %></td>
            <td><%= pokemon.pokemon_id %></td>
            <td>
              <% if (poke_data = PokeApi.get(pokemon: pokemon.pokemon_id)) && poke_data.sprites.present? %>
              <img src=<%= PokeApi.get(pokemon: pokemon.pokemon_id).sprites.front_default %>
              width="50px"
              height="50px" />
              <% end %>
            </td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </center>
</div>

app/views/users/new.html.erb
<%= form_with model: @user, url: sign_up_path do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email, required: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>
  <%= form.submit "Sign Up" %>
<% end %>